Merge into develop
NIAEFEUP/tts-fe pull request #247
Opened 2024-08-14 22:38 UTC by tomaspalma

A feature affected from the refactor that is not being sent to main is the random fill but it will be sent soon enough

2024-08-22 17:37 UTC, thePeras approved these changes
`+8,998 −32,776` Indeed, an intense refactor

✅ 🛫

2024-08-22 18:43 UTC, jose-carlos-sousa approved these changes
LGTM

2024-08-23 18:31 UTC, Process-ing requested changes
It's best to merge #254 first

2024-08-24 08:46 UTC, Process-ing approved these changes

2024-08-24 22:55 UTC, merged