feat: bug reporting by user on the app
NIAEFEUP/tts-fe pull request #324
Opened 2024-10-11 15:20 UTC by tomaspalma

Closes #322.

Adds a form where users can submit bugs.

The design is somewhat experimental, if you don't like it, please say so!

2024-10-11 16:14 UTC, thePeras commented
We want to be limited to just bug reports? Why not suggestions and other types of feedbacks?

2024-10-11 17:13 UTC, tomaspalma commented
> We want to be limited to just bug reports? Why not suggestions and other types of feedbacks?

You're right!

I will add a dropdown for the users to choose whether or not they want to report a bug or suggest feedback

2024-10-13 09:51 UTC, tomaspalma commented
Already changed the position of the bug report on desktop but left it at the original place on mobile.

Also added ability for user to submit bug or suggestion.

2024-10-31 15:10 UTC, thePeras requested changes
This is a really nice new thing. We can next config a slack integration if we want to.

Some things I notice:
- It shouldn't allow submitting empty feedback.
- Can we change the icon? I thinkg the Spider is not the most adequate icon
- The button can be full rounded (circle)?
- When opened, the modal can have a left margin?
- Clear the inputs after submitting
- Add some "Enviado" in the "obrigado" phrase, so that the user knows it was submitted

Also, I think netlify does not have the sentry variables and the feedback is not beeing submited, besides it displays "Obrigado". Maybe a try catch is necessary somewhere

2025-01-31 10:57 UTC, merged