chore: sentry disabled by default in dev mode
NIAEFEUP/tts-fe pull request #329
Opened 2024-10-17 22:26 UTC by tomaspalma

Closes #328 

This takes care of not sending tracing events to sentry when in development.

2024-10-18 08:03 UTC, thePeras requested changes
I think you can use just the `enabled` property.
Read more about [here](https://gist.github.com/MirzaLeka/d709d0925d9b749d1b9068abf4b5ad50)

2024-10-18 08:10 UTC, tomaspalma commented
I understand what you're saying but I was not trying to disable it entirely.

The goal was to allow to disable specific features.

This way I can seamlessly test the bug report without sending tracing reports to sentry.

2024-10-18 08:20 UTC, thePeras commented
> I understand what you're saying but I was not trying to disable it entirely.
> 
> The goal was to allow to disable specific features.
> 
> This way I can seamlessly test the bug report without sending tracing reports to sentry.

Ok, I see

2024-10-18 08:21 UTC, thePeras commented on .env.example
> -SENTRY_AUTH_TOKEN=
I think there is no need for `VITE` prefix here as this env variable is not used in the React app, but in the cli or GitHub CI workflow.

2024-10-31 13:44 UTC, tomaspalma commented on .env.example
> -SENTRY_AUTH_TOKEN=
You are correct.

I removed the `VITE` prefix from that variable.

2024-10-31 15:02 UTC, merged