Collaborative Sessions - Actually create a session [Frontend]
NIAEFEUP/tts-fe pull request #356
Opened 2024-12-30 13:24 UTC by racoelhosilva

This pull request is closely related to ...
It is still a work in progress

2025-01-21 15:18 UTC, tomaspalma requested changes
Great work! I have some questions

When the user joins a new session, it should receive a name. Currently, the name of the user that joins is empty.

2025-01-21 15:18 UTC, tomaspalma commented on src/components/planner/sidebar/sessionController/CollabModal.tsx
> +          link: `http://localhost:3100/planner?session=${sessionsSocket.sessionId}`,
Remove this hardcoded url

2025-01-21 15:18 UTC, tomaspalma commented on src/components/planner/sidebar/sessionController/CollabModal.tsx
> +        toast({ title: 'Sessão criada', description: 'Convida mais amigos para se juntarem!'});
Change "amigos" from "pessoas" :nerd_face:

2025-01-21 15:18 UTC, tomaspalma commented on src/components/planner/sidebar/sessionController/CollabModal.tsx
> +            link: `http://localhost:3100/planner?session=${sessionsSocket.sessionId}`,
Here as well

2025-01-21 21:03 UTC, racoelhosilva commented
> When the user joins a new session, it should receive a name. Currently, the name of the user that joins is empty.

I have been researching this and what I found is that the user is created with a hard-coded name (for now) which I just set to be AnotherUser. However, when this new participant is added, the session he sees is not up-to-date with the actual session (it's as if the user was still not a participant). 

This causes the name not to be displayed as he cannot find a match for his own id in the session. Upon any other update, as the event listeners are now set, the information about the session is correctly updated and this issue does not occur.

This can be tested by changing the name of the creator of the session or joining the session with yet another user (both of which will update the session on the other user).

2025-01-22 14:33 UTC, tomaspalma commented
The name the user has when it first enters the session should not be the same for every user. The way you changed it to right now puts "Anonymous" in everyone.

When the user is authenticated it should put the name of the user. Otherwise it should be a random name like Google Docs and excalidraw does.

You can retrieve the `user` with `useSession()`. If it the `user` is null, it is not authenticated.

If it is not authenticated, generate a random name for example using this library https://github.com/andreasonny83/unique-names-generator

2025-01-23 17:40 UTC, tomaspalma approved these changes

2025-01-23 17:42 UTC, merged